### ISSUE TITLE
NNlib 0.9

### ISSUE THREAD

**Issue by bjarthur** [FluxML/NNlibCUDA.jl#71]
not sure why CompatHelper hasn't issued a PR yet given that its cron is `00 * * * *`, but NNlibCUDA is holding back an upgrade of NNlib to v0.9 b/c it's Project.toml only lists v0.8.15

**Comment by CarloLucibello** [comment]
NNlib v0.9 has incorporated NNlibCUDA as an extension (julia v1.9 only).
The next version of Flux won't depend on NNlibCUDA, which is going to be effectively deprecated and used only for critical backports.

**Comment by bjarthur** [comment]
i see, okay, thanks!

sadly i can not upgrade to 1.9 yet b/c of https://github.com/JuliaLang/julia/issues/49705

**Comment by CarloLucibello** [comment]
that's unfortunate. For the time being the NNlib v0.8 and v0.9 series are identical, except for the extension thing. At some point they will start diverging though, so I hope a julia v1.9 patch release will address the issue soon. 
In any case, feel free to ask for new features to be backported in case you need them.
